#+BEGIN_COMMENT
.. title: org-mode example
.. slug: org-mode-example
.. date: 2016-03-25 12:31:27 UTC
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

* Headline

** Second level

   Hello some text

*** Another third

    Some text over a couple of lines. Some text over a couple of
    lines. Some text over a couple of lines. Some text over a couple
    of lines. Some text over a couple of lines.

*** A Third level

    Some more text


** Another 2nd level

   And some text

   1. poo
   2. poop
   3. pi



   a. Hello
   b. There
      * hello :: He plays Sam
      * list :: He plays Frodo
   c. A list

* Another top level

  hELLO

** Another down

   Hello

** This is a headline

   Still outside the drawer
   :PROPERTIES:
   This is inside the drawer.
   Is everything on a single line,
   Or can I see it all?
   Seems that the nikola org-mode compiler is not handling drawers properly.
   Maybe just use this mode for checkboxes until it is either updated or
   I figure out how to use it.
   :END:
   After the drawer..

   :poop:
   some poop in a drawer.
   poo!
   Need to upgrade org-mode or configure org-drawers for this to work.
   :END:


** Second level
*** Second level

    Hello some text

**** A Third level

     Some more text

**** Another third

     Some text over a couple of lines. Some text over a couple of
     lines. Some text over a couple of lines. Some text over a couple
     of lines. Some text over a couple of lines.

     - A list
     - of some stuff
     - to list


   Hello some text

*** A Third level

    Some more text

*** Another third

    Some text over a couple of lines. Some text over a couple of
    lines. Some text over a couple of lines. Some text over a couple
    of lines. Some text over a couple of lines.

    #+BEGIN_EXAMPLE
    Some example from a text file.
    #+END_EXAMPLE

    #+BEGIN_SRC emacs-lisp
      (defun org-xor (a b)
         "Exclusive or."
         (if a (not b) b))
    #+END_SRC

    There is an issue with using line numbers and refs in code blocks.
    Cannot fontify src block (htmlize.el >= 1.34 required)
    https://github.com/getnikola/plugins/issues/104 Changing conf.py
    to compile with pandoc still does not have these features and
    removes syntax highlighting.

    #+BEGIN_SRC emacs-lisp -n -r
    (save-excursion                  (ref:sc)
       (goto-char (point-min)))      (ref:jump)
    #+END_SRC
    In line [[(sc)]] we remember the current position.  [[(jump)][Line (jump)]]
    jumps to point-min.


    #+BEGIN_SRC emacs-lisp
    (save-excursion
       (Goto-char (point-min)))
    #+END_SRC
    In line [[(sc)]] we remember the current position.  [[(jump)][Line (jump)]]
    jumps to point-min.

    #+BEGIN_SRC python
    print("hello")    # Add a comment
    print("Another Hello") # Add
    range(10)
    #+End_SRC

* TODO Organize party [1/3]
  - [ ] order food
  - [X] think about what music to play
  - [ ] talk to the neighbors
